on:
  pull_request_target:
    branches:
      - "master"
      - "[0-9]+.[0-9]+.z"
    types:
      - closed
jobs:
  close-referenced-prs:
    name: Close referenced PRs
    runs-on: ubuntu-latest
    steps:
      - name: Close referenced PRs
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          CONTENT="$(gh pr view "$PR_NUMBER" --json "body,comments" -q '.body, .comments[].body')"
          
          while read -r line; do
            if [[ $line =~ Closes\ ([^/]+)/([^/]+)#([0-9]+) ]]; then
              OWNER="${BASH_REMATCH[1]}"
              REPO="${BASH_REMATCH[2]}"
              OTHER_PR="${BASH_REMATCH[3]}"
              echo "Closing PR: $OWNER/$REPO/$OTHER_PR"
              REASON=${{ github.event.pull_request.merged && 'merged' || 'closed' }}
              MESSAGE="This pull request has been closed because it was already $REASON as https://github.com/${{ github.repository }}/pull/${PR_NUMBER}"
              gh pr close --repo "$OWNER/$REPO" --comment "$MESSAGE" $OTHER_PR
            fi
          done <<< "$CONTENT"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_WITH_PR_PERMISSIONS }}
